parameters:
    p2_ratchet.assetic.assets_js: [ "js/websocket.js" ]
    p2_ratchet.command.socket_server_command.class: P2\Bundle\RatchetBundle\Command\SocketServerCommand
    p2_ratchet.security.authentication_handler.class: P2\Bundle\RatchetBundle\Security\AuthenticationSuccessHandler
    p2_ratchet.websocket.anonymous_client_provider.class: P2\Bundle\RatchetBundle\WebSocket\Client\AnonymousClientProvider
    p2_ratchet.websocket.connection_manager.class: P2\Bundle\RatchetBundle\WebSocket\Connection\ConnectionManager
    p2_ratchet.websocket.server_bridge.class: P2\Bundle\RatchetBundle\WebSocket\Server\Bridge
    p2_ratchet.websocket.server_factory.class: P2\Bundle\RatchetBundle\WebSocket\Server\Factory
    p2_ratchet.websocket.logger.class: Monolog\Logger
    p2_ratchet.websocket.logger.file: "%kernel.root_dir%/logs/websocket_%kernel.environment%.log"
    p2_ratchet.websocket.logger.name: ServerLog
    p2_ratchet.websocket.logger.stream_handler.class: Monolog\Handler\StreamHandler

services:

    # event dispatcher alias
    p2_ratchet.websocket.event_dispatcher:
        alias: "event_dispatcher"

    # log stream handler
    p2_ratchet.websocket.logger.stream_handler:
        class: "%p2_ratchet.websocket.logger.stream_handler.class%"
        arguments: [ "php://stdout" ]

    # log file handler
    p2_ratchet.websocket.logger.file_handler:
        class: "%p2_ratchet.websocket.logger.stream_handler.class%"
        arguments: [ "%p2_ratchet.websocket.logger.file%" ]

    # server log
    p2_ratchet.websocket.logger:
        class: "%p2_ratchet.websocket.logger.class%"
        arguments:
            - "%p2_ratchet.websocket.logger.name%"
            - [ "@p2_ratchet.websocket.logger.stream_handler", "@p2_ratchet.websocket.logger.file_handler" ]

    # anonymous client provider
    p2_ratchet.websocket.anonymous_client_provider:
        class: "%p2_ratchet.websocket.anonymous_client_provider.class%"

    # client provider default alias
    p2_ratchet.websocket.client_provider:
        alias: "p2_ratchet.websocket.anonymous_client_provider"

    # connection manager
    p2_ratchet.websocket.connection_manager:
        class: "%p2_ratchet.websocket.connection_manager.class%"
        arguments: [ "@p2_ratchet.websocket.client_provider" ]

    # server bridge
    p2_ratchet.websocket.server_bridge:
        class: "%p2_ratchet.websocket.server_bridge.class%"
        arguments:
            - "@p2_ratchet.websocket.connection_manager"
            - "@p2_ratchet.websocket.event_dispatcher"
            - "@p2_ratchet.websocket.logger"

    # server factory
    p2_ratchet.websocket.server_factory:
        class: "%p2_ratchet.websocket.server_factory.class%"
        arguments: [ "@p2_ratchet.websocket.server_bridge" ]

    # console command
    p2_ratchet.command.socket_server_command:
        class: "%p2_ratchet.command.socket_server_command.class%"
        calls:
            - [ setFactory, [ "@p2_ratchet.websocket.server_factory" ]]

    # authentication listener
    p2_ratchet.security.authentication_handler:
        class: "%p2_ratchet.security.authentication_handler.class%"
        arguments: [ "@p2_ratchet.websocket.client_provider" ]
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }
